version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    #environment:
    #  - AZURITE_ACCOUNTS=your-account-name:your-account-key
    volumes:
    - azurite-data:/data

volumes:
  minio-data:
  azurite-data: